## **Tuple**

A tuple is a collection of objects which are immutable and ordered.
Tuples are sequences, just like lists. The differences between tuples and lists are, the tuples cannot be changed unlike lists and tuples use parentheses(), whereas lists use square brackets[].

### Creating a Tuple

In [1]:
ds_lib = ('pandas','numpy','matplotlib','seaborn')
ds_lib

('pandas', 'numpy', 'matplotlib', 'seaborn')

In [2]:
# tuple can store elements of any datatype including list and dictionary also.
tup = (3,6,5.8,['AI',True],'ML',{'name':'Mark'})
print(tup)

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'Mark'})

### Accessing data in tuple

In [3]:
# You can access tuple items by referring to the index number, inside square brackets 
tup = (3,6,5.8,['AI',True],'ML',{'name':'Mark'})
print(tup)

print(tup[3])
print(tup[])

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'Mark'})
['AI', True]

In [4]:
# if we want to access the last element of tuple we can use negative indexing 
tup = (3,6,5.8,['AI',True],'ML',{'name':'Mark'})
print(tup)

print(tup[-1])

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'Mark'})
{'name': 'Mark'}

### Accessing Multiple elements of list - Range of indexes

You can specify a range of indexes by specifying where to start and where to end the range.

When specifying a range, the return value will be a new tuple with the specified items.

In [17]:
# slicing the tuple - using range of index 
tup = (3,6,5.8,['AI',True],'ML',{'name':'Mark'},True)
print(tup)  

# printing first four elements 
print("First four elements  : ",tup[:4]) 

# printing all elements except first three  
print("All elements except first three : ",tup[3:]) 

# printing last two elements 
print("Last two elements : ",tup[-2:]) 

# printing elements within specified range.
print("elements within specifed range : ",tup[2:4])

# printing the elements in reverse order
print("elements in reverse order : ",tup[::-1])

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'Mark'}, True)
First four elements  :  (3, 6, 5.8, ['AI', True])
All elements except first three :  (['AI', True], 'ML', {'name': 'Mark'}, True)
Last two elements :  ({'name': 'Mark'}, True)
elements within specifed range :  (5.8, ['AI', True])
elements in reverse order :  (True, {'name': 'Mark'}, 'ML', ['AI', True], 5.8, 6, 3)

### check if item exist 

To determine if a specified item is present in a tuple use the `in` keyword:

In [32]:
 tup = (3,6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup)  

item = ['AI',True]
if item in tup:
  print("element exist in tuple")
else:
  print("element is not present in a specified tuple ")

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
element exist in tuple

### concatination of tuples

To join two or more tuples we can use the `+` operator:

In [34]:
tup1 = (6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup) 

tup2 = ('universe',45,False)
print(tup2)
print("New tuple after the concatination : ")
tup3 = tup1 + tup2
print(tup3)

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
('universe', 45, False)
New tuple after the concatination :
(6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True, 'universe', 45, False)

### Repeating elements

if we want to repeat the content of a tuple a given number of times, we can use the `*` operator:

In [41]:
rep = ('universe',45,False)
print(rep)
print(rep*3)

('universe', 45, False)
('universe', 45, False, 'universe', 45, False, 'universe', 45, False)

### Built-in Methods that we can Apply on tuples

- count()
- index()
- len()

 - **index() -**
 
Searches the tuple for a specified value and returns the position of where it was found.

**syntax** - *tuple.index(value)*

In [43]:
tup1 = (6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup) 

print(tup1.index('ML'))

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
3

- **count() -**

Returns the number of times a specified value occurs in a tuple.

**syntax -** *tuple.count()*

In [44]:
cnt = (6,5.8,['AI',True],'ML',{'name':'ved'},True,6)
print(cnt)

print(cnt.count(6))

(6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True, 6)
2

- **len() -**

Returns the total number of elements present in a tuple.

In [45]:
tup = (3,6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup)  

print(len(tup))

(3, 6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
7

### Datatype of each element in the tuple

In [46]:
for i in tup:
  print("The datatype of {} is {}".format(i,type(i)))

The datatype of 3 is <class 'int'>
The datatype of 6 is <class 'int'>
The datatype of 5.8 is <class 'float'>
The datatype of ['AI', True] is <class 'list'>
The datatype of ML is <class 'str'>
The datatype of {'name': 'ved'} is <class 'dict'>
The datatype of True is <class 'bool'>

### Loop through a Tuple

We can loop through the tuple items by using a for loop.

In [70]:
tup1 = (6,5.8,['AI',True],'ML',{'name':'ved'},True)

for i in tup1:
  print(i)

6
5.8
['AI', True]
ML
{'name': 'ved'}
True

Looping through index number using while loop

In [73]:
#printing the elements of the tuple with their respective index using while loop 
tup1 = (6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup1)

length=len(tup1)
i=0
while(i<length):
  print("Element at Positon {} is {}".format(i,tup1[i]))
  i+=1

(6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
Element at Positon 0 is 6
Element at Positon 1 is 5.8
Element at Positon 2 is ['AI', True]
Element at Positon 3 is ML
Element at Positon 4 is {'name': 'ved'}
Element at Positon 5 is True

Looping through index number using for loop 

using `range()` and `len()` function

In [74]:
tup1 = (6,5.8,['AI',True],'ML',{'name':'ved'},True)
print(tup1)

for i in range((len(tup1))):
  print("Element at Positon {} is {}".format(i,tup1[i]))

(6, 5.8, ['AI', True], 'ML', {'name': 'ved'}, True)
Element at Positon 0 is 6
Element at Positon 1 is 5.8
Element at Positon 2 is ['AI', True]
Element at Positon 3 is ML
Element at Positon 4 is {'name': 'ved'}
Element at Positon 5 is True